### ISSUE TITLE
Missing lang key

### ISSUE THREAD

**Issue by ChromaPIE** [necauqua/subpocket#1]
The missing key is `subpocket.popup.blocked_ender_chest`. Maybe the existing `popup.subpocket:blocked_ender_chest` is intended to be this.

Also, typo of line 52 in en_us.lang : pla**t**er <=> player

**Comment by necauqua** [comment]
Hey mentioning to you that I noticed this issue (and also the one where forge keeps thinking that this mod has an update), thanks, would fix it like tomorrow or even a bit later because it was kinda hard for last 2 days with cyberpunk being so good and actual electricity outages at my place, yeah
