### ISSUE TITLE
No idea how to use... need tutorial...

### ISSUE THREAD

**Issue by sapioit** [necauqua/subpocket#1]
As you can see [here](https://mods.curse.com/mc-mods/minecraft/275425-subpocket?comment=1), nobody knows how to use your mod... please include step-by-step screenshots that show us how to use this mod!

**Comment by necauqua** [comment]
You just type the code while playing the game to open the GUI.
I've clarified a bit on that in Curse description.
Maybe in future i'll add some more clarifications right in the game.

You're asking for screenshots, but what screenshots can i give you? :d
Of me completing 'tasks'? Like can't you read, it's all pretty clear.

I'll make so that '/subpocket show' and '/subpocket get' works without op.

**Comment by sapioit** [comment]
Thanks! 
I thought there was something more difficult... like needing a certain item, or something like that...
Also, `/subpocket show` (`\``, not `'`) working without OP is something I thought was the way to access the pocket... Personally, I would remove the code and add a in-game keybind to open the pocket... and have that kebind show up in Minecraft's Controls page...

**Comment by necauqua** [comment]
Well, that is the obvious way of course.
The code you have to remember and type is another level of diffuculty because, y'know, infinite storage, OP.

**Comment by sapioit** [comment]
I would rather have to need to have entered different items into the storage, to unlock more storage slots, but that would require more programming.

**Comment by necauqua** [comment]
The whole point of the mod is the _infinite_ storage. Yes, OP, but thats how it was designed from the beginning.

**Comment by sapioit** [comment]
What I'm trying to say is: if you make the items needed for upgrade to be listed in the config files, you could default it as needing no item to upgrade infinite storage, but let the server owners and single players set their own rules for unlocking more of the infinite storage.

**Comment by necauqua** [comment]
> to upgrade infinite storage

Huh, sounds a bit absurely, can't you see :D
I won't change this, as it is the core mechanic of the mod.
If server owners don't want infinite storage they are free not to install this mod, as it _explicitly_ states that the main thing it offers is the infinite storage.

Try to play in survival with it (and also the more other mods(and hence - item types) you have - the better). You'll very quickly end up with a mess in small subpocket field, which is the anti-OP drawback and you can sort stuff only by your hands with no other sorting methods ever available.
