### ISSUE TITLE
[ENH] A proper number formatter for large quantities

### ISSUE THREAD

**Issue by Wabbit0101** [necauqua/subpocket#2]
Nice mod; one enhancement request: rather than showing the quantity as a big ol' flat number, it might be nice to have a proper rounding formatter (so '12.34M' instead of 12345678 ). There could be a config to indicate at what quantity this contraction begins (eg after 10000 of something just show me 10.1K instead of 10100 etc.)

**Comment by Wabbit0101** [comment]
...nevermind...player was looking at tooltip instead of subpocket screen.

**Comment by necauqua** [comment]
[Yeah](https://github.com/necauqua/subpocket/blob/main/src/api/java/dev/necauqua/mods/subpocket/api/ISubpocketStack.java#L20) :)
