### ISSUE TITLE
Crash with sophisticated backpacks

### ISSUE THREAD

**Issue by Keltas** [necauqua/subpocket#4]
I have put a backpack from the sophisticated backpacks mod into the subpocket, which resulted in the game crashing a moment after opening it. I am pretty sure that that was the cause as using NBT Explorer to delete the backpack from the subpocket stopped the crashing. I am attaching the crash report.
Versions used: subpocket-1.18-8.0.1.0.jar, sophisticatedbackpacks-1.18.1-3.15.1.505.jar forge 39.0.64 for minecraft 1.18.1

[crash-2022-02-04_22.28.13-client.txt](https://github.com/necauqua/subpocket/files/8006643/crash-2022-02-04_22.28.13-client.txt)
.

**Comment by necauqua** [comment]
That's a great report, thanks, will look into it

**Comment by necauqua** [comment]
Yeah the fix was easy, they did something I did not expect them to do in the backpack item rendering.

I want to make a release once I fix #3, meanwhile if you really want to you can grab the build artifact for this commit [here](https://github.com/necauqua/subpocket/actions/runs/1797999787)
